# Generated by Django 5.0.6 on 2024-07-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='education_level',
            field=models.CharField(choices=[('primary', 'Szkoła podstawowa'), ('secondary', 'Szkoła średnia')], default='primary', max_length=50),
        ),
    ]
