# Generated by Django 5.0.6 on 2024-07-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_mathtest_mathtask_score_delete_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mathtest',
            name='topic',
        ),
        migrations.AddField(
            model_name='mathtest',
            name='level',
            field=models.CharField(choices=[('egzamin8', 'Egzamin ósmoklasisty'), ('matura', 'Matura')], default='egzamin8', max_length=100),
        ),
    ]
